### PR TITLE
Nice style change

### PR DESCRIPTION
**Pull request by donut28**
Accessibility mostly passed, the only thing that failed is AAA small text.
image

### CODE REVIEW

**Review by no1crate — CHANGES_REQUESTED** [review]
Hey.
I don't think about any color change. I prefer it black and white, I could consider the font change, but the color is the only thing I will not to change.

**Comment by donut28** [comment]
Alright, I'll fix it now.

**Comment by no1crate** [comment]
Great!

**Comment by donut28** [comment]
All done.

**Review by no1crate — APPROVED** [review]
Passes

**Pull request merged**
